# Generated by Django 4.2.4 on 2023-09-16 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdb',
            name='time_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
