# Generated by Django 4.2.4 on 2024-06-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0003_locationinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlumapsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('community_need', models.TextField(blank=True, null=True)),
                ('commerce_need', models.TextField(blank=True, null=True)),
                ('private_need', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
