# Generated by Django 3.2.25 on 2025-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0004_blumapstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('GeoHash', models.CharField(blank=True, max_length=12, null=True)),
                ('Description', models.TextField()),
                ('Category', models.CharField(choices=[('Community', 'Community'), ('Commerce', 'Commerce'), ('Private', 'Private')], max_length=50)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Priority', models.CharField(default='Medium', max_length=20)),
                ('Tags', models.JSONField(blank=True, null=True)),
                ('Attachments', models.JSONField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('Resolved_Date', models.DateTimeField(blank=True, null=True)),
                ('Created_By', models.CharField(blank=True, max_length=255, null=True)),
                ('Updated_By', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
