# Generated by Django 3.2.25 on 2025-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0005_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Priority',
            field=models.CharField(blank=True, default='Medium', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
    ]
