# Generated by Django 3.2.25 on 2025-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0009_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
