name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # Adjust based on testing framework

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}  # EC2 IP address
          USER: ${{ secrets.EC2_USER }}  # EC2 Username (e.g., 'ubuntu')
          KEY: ${{ secrets.EC2_SSH_KEY }}  # Private SSH key (stored as secret)
        run: |
          # Save the private key to a file
          echo "${KEY}" > private_key.pem
          chmod 600 private_key.pem
          
          # SSH into EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} << 'EOF'
            cd blumap  # Update with your actual project path
            git pull origin master  
            source venv/bin/activate  # Adjust if necessary
            pip install -r requirements.txt
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput  
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn  # Restart gunicorn to apply changes
            sudo systemctl enable gunicorn
          EOF
