name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # Adjust based on testing framework

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}  # ip
          USER: ${{ secrets.EC2_USER }}    # username 
          KEY: ${{ secrets.EC2_SSH_KEY }}   # private SSH key
        run: |
          echo "${KEY}" > ../U2.pem  
          chmod 600 ../U2.pem         
          ssh -o StrictHostKeyChecking=no -i ../ec2_key.pem ${USER}@${HOST} << 'EOF'
            cd /blumap  
            git pull origin main  
            source venv/bin/activate 
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput  
            sudo systemctl restart your_service 
          EOF
