name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}  # Your EC2 instance public IP or DNS
          USER: ${{ secrets.EC2_USER }}    # Your EC2 username (e.g., ec2-user)
          KEY: ${{ secrets.EC2_SSH_KEY }}   # Your private SSH key
        run: |
          echo "${KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${USER}@${HOST} << 'EOF'
            cd /path/to/your/project  # Change to your project directory
            git pull origin main       # Pull the latest changes
            source venv/bin/activate    # Activate your virtual environment
            pip install -r requirements.txt  # Install dependencies
            python manage.py migrate    # Apply migrations
            python manage.py collectstatic --noinput  # Collect static files
            sudo systemctl restart your_service  # Restart your service (if applicable)
          EOF
